version: "3"

networks:
  backend:
    driver: bridge

services:
  master:
    build:
      context: ./master
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes: 
      - ./master/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d 
    ports:
      - 3330:3306
    networks:
      - backend

  slave1:
    build:
      context: ./slave1
    depends_on:
      - master
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes: 
      - ./slave1/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d 
    ports:
      - 3331:3306
    networks:
      - backend

  slave2:
    build:
      context: ./slave2
    depends_on:
      - master
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes: 
      - ./slave2/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d 
    ports:
      - 3332:3306
    networks:
      - backend
